name: "tagged-release"

on:
  push:
    tags:
      - "1.1.0.0"

jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
